config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    resources :votes, only: [:index, :create]
  end

  resources :problems

  get 'profiles/:id', :controller => 'profiles', :action => 'show'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'discourse/sso', :controller => 'discourse_sso', :action => 'sso'

  root to: 'pages#home'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get 'locations/', controller: 'locations', action: 'provinces'
      get 'locations/:province_id/', controller: 'locations', action: 'kabupatens'
      get 'locations/:province_id/:kabupaten_id/', controller: 'locations', action: 'kecamatans'
      get 'locations/:province_id/:kabupaten_id/:kecamatan_id', controller: 'locations', action: 'kelurahans'

      scope 'problems' do
        resources :maps, only: [:index], controller: 'problems/maps'
        resources :details, only: [:index, :show], concerns: :votable, controller: 'problems/details', defaults: {model_name: 'Problem'} do
          resources :findings, only: [:index, :create, :destroy], concerns: :votable, controller: 'problems/findings', defaults: {model_name: 'Finding'}
        end
        resources :categories, only: [:index], controller: 'problems/categories'
      end
    end
  end

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :reported_by, class_name: "User"
  belongs_to :province
  belongs_to :kabupaten
  belongs_to :kecamatan
  belongs_to :kelurahan

  validates :title, :summary, :category_id, :province, :kabupaten, :kecamatan, :kelurahan, :urgency, :address, :presence => true
  before_validation :remove_empty_images

  geocoded_by :address_with_province
  after_validation :geocode

  before_save :set_total_point, :set_latitude_longitude_if_geocode_fail

  acts_as_votable

  def self.all_categories
    return [["Kesehatan", 0], ["Pendidikan", 1], ["Hukum", 2]]
  end

  def self.all_urgencies
    return [["Sangat rendah", 0], ["Rendah", 1], ["Menengah", 2], ["Penting", 3], ["Kritikal", 4]]
  end

  def category_name
    Problem.all_categories[self.category_id][0]
  end

  def urgency_name
    Problem.all_urgencies[self.urgency][0]
  end

  def province_name
    return self.province.name
  end

  def kabupaten_name
    return self.kabupaten.name
  end

  def kecamatan_name
    return self.kecamatan.name
  end

  def kelurahan_name
    return self.kelurahan.name
  end

  def address_with_province
    return self.address + ", " + self.province.name
  end

  def remove_empty_images
    if self.images
      new_images = self.images.inject([]) do |res, image|
        if image and image.length > 0
          res.append(image)
        else
          res
        end
      end
      self.images = new_images
    end
  end

  def set_total_point
    sign = if self.cached_votes_up >= self.cached_votes_down then 1 else -1 end
    normalized_vote_point = sign * Math.log2((self.cached_votes_up - self.cached_votes_down).abs + 1).to_i

    base = 1406818754 #31 July 2014
    if self.created_at
      time_point = (self.created_at.to_i - base) / 15000
    else
      time_point = (Time.now.to_i - base) / 15000
    end

    self.total_point = normalized_vote_point + time_point
  end

  def set_latitude_longitude_if_geocode_fail
    unless (self.latitude? and self.longitude?)
      puts self.kelurahan.latitude
      puts self.kelurahan.longitude
      self.latitude = self.kelurahan.latitude
      self.longitude = self.kelurahan.longitude
    end
  end
end

app/controllers/api/v1/problems/categories_controller.rb
class Api::V1::Problems::CategoriesController < Api::V1::BaseApisController
  def index
    @categories = Problem.all_categories
  end
end

app/controllers/api/v1/problems/details_controller.rb
class Api::V1::Problems::DetailsController < Api::V1::BaseApisController
  def index
    @problems = Problem.includes([:reported_by, :province, :kabupaten, :kecamatan, :kelurahan])

    @problems = @problems.where(province_id: params[:province_id].to_i) if params[:province_id]
    @problems = @problems.where(kabupaten_id: params[:kabupaten_id].to_i) if params[:kabupaten_id]
    @problems = @problems.where(kecamatan_id: params[:kecamatan_id].to_i) if params[:kecamatan_id]
    @problems = @problems.where(kelurahan_id: params[:kelurahan_id].to_i) if params[:kelurahan_id]
    @problems = @problems.where(category_id: params[:category_id].to_i) if params[:category_id]

    if params[:order]
      case params[:order]
        when "popular"
          @problems = @problems.order('cached_votes_up - cached_votes_down').reverse_order
        when "latest"
          @problems = @problems.order('created_at').reverse_order
      end
    else
      # hot
      @problems = @problems.order("total_point").reverse_order
    end

    if params[:latitude] and params[:longitude]
      @problems = @problems.near([params[:latitude], params[:longitude]], 20)
    end

    @problems = @problems.paginate(page: params[:page], per_page: 20)
  end

  def show
    @problem = Problem.includes([:reported_by, :province, :kabupaten, :kecamatan, :kelurahan]).find(params[:id])
  end
end

app/controllers/api/v1/problems/findings_controller.rb
class Api::V1::Problems::FindingsController < Api::V1::BaseApisController
  before_action :authenticate_user_json!, only: [:create]

  def index
    detail_id = params[:detail_id].to_i
    @findings = Finding.includes(:user).where(problem_id: detail_id).hash_tree
  end

  def create
    if params[:finding][:parent_id]
      parent = Finding.find(params[:finding].delete(:parent_id))
      @finding = parent.children.build(finding_params)
    else
      @finding = Finding.new(finding_params)
    end

    @finding.user = current_user
    @finding.problem_id = params[:detail_id].to_i

    if @finding.save
      render json: {status: 'created'}
    else
      render status: :unprocessable_entity
    end
  end

  def finding_params
    params.require(:finding).permit(:comment)
  end

  def destroy
    finding = Finding.find(params[:id])

    if (finding.user != current_user)
      render status: :unauthorized
    else
      finding.destroy

      render json: {status: 'deleted'}
    end
  end
end

app/controllers/api/v1/problems/maps_controller.rb
class Api::V1::Problems::MapsController < Api::V1::BaseApisController
  def index
    @problems = Problem.includes(:kelurahan)

    @problems = @problems.where(province_id: params[:province_id].to_i) if params[:province_id]
    @problems = @problems.where(kabupaten_id: params[:kabupaten_id].to_i) if params[:kabupaten_id]
    @problems = @problems.where(kecamatan_id: params[:kecamatan_id].to_i) if params[:kecamatan_id]
    @problems = @problems.where(kelurahan_id: params[:kelurahan_id].to_i) if params[:kelurahan_id]
    @problems = @problems.where(category_id: params[:category_id].to_i) if params[:category_id]

    if params[:latitude] and params[:longitude]
      @problems = @problems.near([params[:latitude], params[:longitude]], 20)
    end
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /problems
  # GET /problems.json
  def index
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    gon.problem_id = params[:id]
    @brainstorm_url = "http://#{params[:id]}.discourse.gotong.royong.org/session/sso?return_path=%2F"
  end

  # GET /problems/new
  def new
    @problem = Problem.new
    @problem.images = []
    initialize_locations(@problem)
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
  end

  # GET /problems/1/edit
  def edit
    if @problem.reported_by == current_user
      initialize_locations(@problem)
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
    else
      redirect_to problem_path(@problem)
    end
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)
    @problem.reported_by = current_user

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html {
          initialize_locations(@problem)
          @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
          render :new
        }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    if @problem.reported_by == current_user
      respond_to do |format|
        if @problem.update(problem_params)
          format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
          format.json { render :show, status: :ok, location: @problem }
        else
          format.html {
            initialize_locations(@problem)
            @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
            render :edit
          }
          format.json { render json: @problem.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to problem_path(@problem)
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    if @problem.reported_by == current_user
      @problem.destroy
      respond_to do |format|
        format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to problem_path(@problem)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:title, :category_id, :summary, :cause, :symptom, :effect, :urgency, :address,
                                      :province_id, :kabupaten_id, :kecamatan_id, :kelurahan_id, :reported_by, :images => [])
    end

    def initialize_locations(problem)
      gon.province_id = problem.province_id
      gon.kabupaten_id = problem.kabupaten_id
      gon.kecamatan_id = problem.kecamatan_id
      gon.kelurahan_id = problem.kelurahan_id
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
  def long_lat_points(problems)
    res = []
    problems.each do |problem|
      res.append([problem.kecamatan.latitude, problem.kecamatan.longitude])
    end
    return res.to_json
  end
end

app/views/problems/_form.html.haml
:javascript
  $(function() {
    $('#problemForm').find("input:file").each(function(i, elem) {
      var fileInput    = $(elem);
      var form         = $(fileInput.parents('form:first'));
      var submitButton = form.find('input[type="submit"]');
      var progressBar  = $("<div class='progress-bar progress-bar-success progress-bar-striped' role='progressbar' aria-valuenow='0' aria-valuemin='0' aria-valuemax='100'></div>");
      var barContainer = $("<div class='progress' style='margin-top:10px; display:none'></div>").append(progressBar);
      fileInput.after(barContainer);
      fileInput.fileupload({
        fileInput:       fileInput,
        url:             '#{@s3_direct_post.url}',
        type:            'POST',
        autoUpload:       true,
        formData:         #{@s3_direct_post.fields.to_json.html_safe},
        paramName:        'file', // S3 does not like nested name fields i.e. name="user[avatar_url]"
        dataType:         'XML',  // S3 returns XML if success_action_status is set to 201
        replaceFileInput: false,
        progressall: function (e, data) {
          var progress = parseInt(data.loaded / data.total * 100, 10);
          progressBar.
            css('width', progress + '%').
            attr('aria-valuenow', progress);
        },
        start: function (e) {
          submitButton.prop('disabled', true);
          barContainer.show();
          progressBar.
            css('width', '0%').
            attr('aria-valuenow', 0).
            removeClass("progress-bar-danger").
            addClass("progress-bar-success").
            text("Loading...");
        },
        done: function(e, data) {
          submitButton.prop('disabled', false);
          progressBar.text("Uploading done");

          // extract key and generate URL from response
          var key   = $(data.jqXHR.responseXML).find("Key").text();
          var url   = '//#{@s3_direct_post.url.host}/' + key;

          // create hidden field
          //var input = $("<input />", { type:'hidden', name: fileInput.attr(' name'), value: url })
          fileInput.nextAll(":hidden:first").val(url);
        },
        fail: function(e, data) {
          submitButton.prop('disabled', false);

          progressBar.
            removeClass("progress-bar-success").
            addClass("progress-bar-danger").
            text("Failed");
        }
      });
    });
  });

.row{'ng-app' => 'problemApp', 'ng-controller' => 'NewProblemController as vm'}
  .col-sm-9
    = form_for @problem, html: {class:'form-horizontal', id:'problemForm'} do |f|
      - if @problem.errors.any?
        #error_explanation
          .alert.alert-danger
            %h4= "#{pluralize(@problem.errors.count, "error")} prohibited this problem from being saved:"
            %ul
              - @problem.errors.full_messages.each do |msg|
                %li= msg

      .form-group
        = f.label :title, class: 'col-sm-2 control-label'
        .col-sm-10
          = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :image, class: 'col-sm-2 control-label'
        .col-sm-10
          = render partial: "image_uploader", locals: {existing_image_url: @problem.images[0]}
          %br
          = render partial: "image_uploader", locals: {existing_image_url: @problem.images[1]}
          %br
          = render partial: "image_uploader", locals: {existing_image_url: @problem.images[2]}
          %br
          = render partial: "image_uploader", locals: {existing_image_url: @problem.images[3]}
          %br
          = render partial: "image_uploader", locals: {existing_image_url: @problem.images[4]}
      .form-group
        = f.label :category_id, class: 'col-sm-2 control-label'
        .col-sm-3
          = f.select :category_id, Problem.all_categories, {}, {class: 'form-control'}
      .form-group
        = f.label :summary, class: 'col-sm-2 control-label'
        .col-sm-10
          = f.text_area :summary, class: 'form-control', style: 'height: 300px'
      .form-group
        = f.label :cause, class: 'col-sm-2 control-label'
        .col-sm-10
          = f.text_area :cause, class: 'form-control'
      .form-group
        = f.label :symptom, class: 'col-sm-2 control-label'
        .col-sm-10
          = f.text_area :symptom, class: 'form-control'
      .form-group
        = f.label :effect, class: 'col-sm-2 control-label'
        .col-sm-10
          = f.text_area :effect, class: 'form-control'
      .form-group
        = f.label :urgency, class: 'col-sm-2 control-label'
        .col-sm-2
          = f.select :urgency, Problem.all_urgencies, {}, {class: 'form-control'}
      .form-group
        = f.label :lokasi, class: 'col-sm-2 control-label'
        .col-sm-2
          = f.select :province_id, [], {}, {'ng-model' => 'vm.selectedProvince',
            'ng-options' => 'province.name for province in vm.provinces track by province.id', 'ng-change' => 'vm.getKabupatens()',
            class: 'form-control'}
        .col-sm-2{'ng-if' => 'vm.kabupatens.length > 0'}
          = f.select :kabupaten_id, [], {}, {'ng-model' => 'vm.selectedKabupaten',
            'ng-options' => 'kabupaten.name for kabupaten in vm.kabupatens track by kabupaten.id', 'ng-change' => 'vm.getKecamatans()',
            class: 'form-control'}
        .col-sm-2{'ng-if' => 'vm.kecamatans.length > 0'}
          = f.select :kecamatan_id, [], {}, {'ng-model' => 'vm.selectedKecamatan',
            'ng-options' => 'kecamatan.name for kecamatan in vm.kecamatans track by kecamatan.id', 'ng-change' => 'vm.getKelurahans()',
            class: 'form-control'}
        .col-sm-2{'ng-if' => 'vm.kelurahans.length > 0'}
          = f.select :kelurahan_id, [], {}, {'ng-model' => 'vm.selectedKelurahan',
            'ng-options' => 'kelurahan.name for kelurahan in vm.kelurahans track by kelurahan.id', class: 'form-control'}
      .form-group
        = f.label "Alamat lengkap", class: 'col-sm-2 control-label'
        .col-sm-10
          = f.text_field :address, class: 'form-control'
      .form-group
        .col-sm-10.col-sm-offset-2
          = f.submit 'Save', class: 'btn btn-primary'

app/views/problems/_image_uploader.html.haml
= file_field_tag 'problem[images_dummy][]'
= hidden_field_tag 'problem[images][]', existing_image_url
-if existing_image_url
  %a.thumbnail.thumb
    %img{'src' => existing_image_url}

app/views/problems/edit.html.haml
%h2 Editing problem

= render 'form'

app/views/problems/index.html.haml
-content_for :header do
  %script{src: 'https://maps.googleapis.com/maps/api/js?v=3.exp'}
  -#google.maps.event.addDomListener window, "load", initialize

%div{'ng-app' => 'problemApp', 'ng-controller' => 'IndexProblemController as vm'}
  .row
    .col-sm-9
      #map-canvas
    .col-sm-3{'ng-cloak' => true}
      .row
        .col-sm-4{class: 'col-sm-2 control-label'} Provinsi
        .col-sm-8
          = select_tag :province_id, {}, {'ng-model' => 'vm.filter.province',
            'ng-options' => 'province.name for province in vm.provinces track by province.id', 'ng-change' => 'vm.getKabupatens(vm.filter.province)',
            class: 'form-control'}
      .row.location-filter
        .col-sm-4{class: 'col-sm-2 control-label'} Kabupaten
        .col-sm-8
          = select_tag :kabupaten_id, {}, {'ng-model' => 'vm.filter.kabupaten',
            'ng-options' => 'kabupaten.name for kabupaten in vm.kabupatens track by kabupaten.id', 'ng-change' => 'vm.getKecamatans(vm.filter.province, vm.filter.kabupaten)',
            class: 'form-control'}
      .row.location-filter
        .col-sm-4{class: 'col-sm-2 control-label'} Kecamatan
        .col-sm-8
          = select_tag :kecamatan_id, {}, {'ng-model' => 'vm.filter.kecamatan',
            'ng-options' => 'kecamatan.name for kecamatan in vm.kecamatans track by kecamatan.id', 'ng-change' => 'vm.getKelurahans(vm.filter.province, vm.filter.kabupaten, vm.filter.kecamatan)',
            class: 'form-control'}
      .row.location-filter
        .col-sm-4{class: 'col-sm-2 control-label'} Kelurahan
        .col-sm-8
          = select_tag :kecamatan_id, {}, {'ng-model' => 'vm.filter.kelurahan',
            'ng-options' => 'kelurahan.name for kelurahan in vm.kelurahans track by kelurahan.id', class: 'form-control'}
      %hr
      .row.location-filter
        .col-sm-4{class: 'col-sm-2 control-label'} Kategori
        .col-sm-8
          = select_tag :category_id, {}, {'ng-model' => 'vm.filter.category',
            'ng-options' => 'category.name for category in vm.categories track by category.id',
            class: 'form-control'}

      .row.location-filter
        .col-sm-8.col-sm-offset-4
          %a{'class' => 'btn btn-primary btn-md', 'ng-click' => 'vm.filterProblems(vm.filter, false)'}
            %span.glyphicon.glyphicon-search
            Search all
          %a{'class' => 'btn btn-success btn-md', 'ng-click' => 'vm.filterProblems(vm.filter, true)'}
            %span.glyphicon.glyphicon-globe
            Near me
  .row
    .col-sm-12
      .pull-right
        = link_to new_problem_path, class: 'btn btn-primary' do
          %span.glyphicon.glyphicon-plus
          New Problem
  .row{'ng-cloak' => true}
    .col-sm-12
      %ul.nav.nav-pills.pull-left
        %li{'ng-class' => "vm.filter.order == -1 ? 'active' : ''"}
          %a.thumb{'ng-click' => "vm.orderProblems(-1)"} Hot
        %li{'ng-class' => "vm.filter.order == 'popular' ? 'active' : ''"}
          %a.thumb{'ng-click' => "vm.orderProblems('popular')"} Popular
        %li{'ng-class' => "vm.filter.order == 'latest' ? 'active' : ''"}
          %a.thumb{'ng-click' => "vm.orderProblems('latest')"} Latest
      .pager{'ng-if' => 'vm.total_pages > 1', style: 'margin:0px'}
        %a.btn.btn-success.btn-sm{"ng-click" => 'vm.fetchPrevPage()', "ng-if" => 'vm.current_page > 1', style: 'margin-right:5px'}
          %span.glyphicon.glyphicon-chevron-left
          Prev
        Page {{vm.current_page}} / {{vm.total_pages}}
        %a.btn.btn-success.btn-sm{"ng-click" => 'vm.fetchNextPage()', "ng-if" => 'vm.current_page < vm.total_pages', style: 'margin-left:5px'}
          Next
          %span.glyphicon.glyphicon-chevron-right
  .row{style: 'margin-top:20px', 'ng-cloak' => true}
    .col-sm-12
      %ul.media-list
        %li.media{'ng-repeat' => 'problem in vm.detailedProblems'}
          .pull-left.vote-counter
            %b
              {{problem.up_vote - problem.down_vote}}
              %br
              votes
          %a.pull-left
            %img.media-object.thumbnail{'ng-src' => '{{problem.images[0]}}', 'ng-if' => 'problem.images.length > 0'}
            %img.media-object.thumbnail{'src' => image_path("404.png"), 'ng-if' => '!problem.images || problem.images.length == 0'}
          .media-body
            .col-sm-12
              %h4
                %a{'ng-href'=>'{{problem.url}}'}
                  {{problem.title}}
            .col-sm-8
              %p.summary
                "{{problem.summary | limitTo:800}}"
            .col-sm-4
              .col-sm-3
                %b Category
              .col-sm-9
                {{problem.category_name}}
              .col-sm-3
                %b Urgency
              .col-sm-9
                .progress
                  .progress-bar.progress-bar-success.progress-bar-striped.active{"aria-valuemax" => "5", "aria-valuemin" => "0", "aria-valuenow" => "{{vm.problem.urgency + 1}}",
                    :role => "progressbar", 'ng-style' => "{'width': ((problem.urgency + 1) * 100.0 / 5.0) + '%'}"}
              .col-sm-3
                %b Location
              .col-sm-9
                {{problem.kelurahan_name}}, {{problem.kecamatan_name}}, {{problem.kabupaten_name}}, {{problem.province_name}}
              .col-sm-3
                %b Reporter
              .col-sm-9
                {{problem.reported_by_name}}
            .clearfix

app/views/problems/new.html.haml
%h2 New problem

= render 'form'

app/views/problems/show.html.haml
=content_for :header do
  = javascript_include_tag 'iframeResizer.min'

  :coffeescript
    $(document).ready ->      
      $('iframe').iFrameResize();

.row{'ng-app' => 'problemApp', 'ng-controller' => 'ShowProblemController as vm'}
  .col-sm-6
    .pull-left{style: 'margin-right: 20px; margin-bottom: 5px; margin-left:10px; margin-top: 20px', 'ng-cloak' => true}
      %vote-section{'is-owner' => 'vm.problem.is_owner', 'vote-up' => 'vm.vote_up()', 'vote-down' => 'vm.vote_down()', 'vote-status' => '{{vm.vote.my_vote_status}}', 'up-vote-count' => '{{vm.vote.up_vote}}', 'down-vote-count' => '{{vm.vote.down_vote}}', 'img-style' => '{{vm.voteImgStyle}}'}
      = link_to edit_problem_path(params[:id]), class: 'btn btn-info btn-sm', style: 'margin-top:20px', 'ng-if' => 'vm.problem.is_owner' do
        %span.glyphicon.glyphicon-edit
      = button_to problem_path(params[:id]), method: :delete, data: {confirm: "Are you sure want to delete this problem?"}, 'ng-if' => 'vm.problem.is_owner', class: 'btn btn-danger btn-sm', style: 'margin-top:20px' do
        %span.glyphicon.glyphicon-trash
    %div{style: 'overflow: hidden', 'ng-cloak' => true}
      %h4
        {{vm.problem.title}}
      / Nav tabs
      %ul.nav.nav-tabs{:role => "tablist"}
        %li.active
          %a{"data-toggle" => "tab", :href => "#overview", :role => "tab"}
            %span.glyphicon.glyphicon-home
            Overview
        %li
          %a{"data-toggle" => "tab", :href => "#cause", :role => "tab"}
            %span.glyphicon.glyphicon-fire
            Cause
        %li
          %a{"data-toggle" => "tab", :href => "#symptom", :role => "tab"}
            %span.glyphicon.glyphicon-eye-open
            Symptom
        %li
          %a{"data-toggle" => "tab", :href => "#effect", :role => "tab"}
            %span.glyphicon.glyphicon-screenshot
            Effect
      / Tab panes
      .tab-content{style: 'margin: 10px'}
        #overview.tab-pane.active
          .row
            .col-sm-2
              Urgency
            .col-sm-3
              .progress
                .progress-bar.progress-bar-success.progress-bar-striped.active{"aria-valuemax" => "5", "aria-valuemin" => "0", "aria-valuenow" => "{{vm.problem.urgency + 1}}",
                  :role => "progressbar", 'ng-style' => "{'width': ((vm.problem.urgency + 1) * 100.0 / 5.0) + '%'}"}
            .col-sm-1
            .col-sm-2
              Category
            .col-sm-3
              {{vm.problem.category_name}}
          .row
            .col-sm-2
              Location
            .col-sm-10
              {{vm.problem.address}}
              %br
              {{vm.problem.kelurahan_name}},
              {{vm.problem.kecamatan_name}},
              {{vm.problem.kabupaten_name}},
              {{vm.problem.province_name}}
          .row
            .col-sm-2
              Reporter
            .col-sm-10
              {{vm.problem.reported_by.name}}
          .row
            .col-sm-2{'ng-repeat' => 'image in vm.problem.images track by $index', style: 'padding-left:5px; padding-right:5px'}
              %a.thumbnail.thumb{"data-toggle" => "lightbox", 'ng-click' => "vm.showImage($index)", style: 'width:100%'}
                %img{'ng-src' => '{{image}}'}
              .demoLightbox.lightbox.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
                .lightbox-dialog
                  .lightbox-content
                    %img{'ng-src' => '{{image}}'}

          .row
            .bs-callout.bs-callout-info
              .with-newline<
                {{vm.problem.summary}}
        #cause.tab-pane
          .row
            .col-sm-12.with-newline<
              {{vm.problem.cause}}
        #symptom.tab-pane
          .row
            .col-sm-12.with-newline<
              {{vm.problem.symptom}}
        #effect.tab-pane
          .row
            .col-sm-12.with-newline<
              {{vm.problem.effect}}
    .clearfix

    %hr

    %ul.nav.nav-pills{:role => "tablist"}
      %li.active
        %a{"data-toggle" => "tab", :href => "#findings", :role => "tab"}
          %span.glyphicon.glyphicon-search
          Findings
      %li
        %a{"data-toggle" => "tab", :href => "#volunteers", :role => "tab"}
          %span.glyphicon.glyphicon-user
          Volunteers
      %li
        %a{"data-toggle" => "tab", :href => "#fundings", :role => "tab"}
          %span.glyphicon.glyphicon-usd
          Fundings

    .tab-content{style: 'margin: 10px'}
      #findings.tab-pane.active
        =render partial: 'findings/index'
      #volunteers.tab-pane
        %h4 Volunteers
      #fundings.tab-pane
        %h4 Fundings

  .col-sm-6{style: 'height:100%'}
    %h4 Brainstorm for solution
    %iframe{'src' => "#{@brainstorm_url}", width: '100%', scrolling: "no",
      style: 'overflow:hidden;width:100%', frameborder: 0}